function methods = setup_methods_and_ba

    addpath('/home/alexander/materials/pnpl/pnpl/opnp');
    
    fs = {        
        @(p,l,vp,vl)slv.sego_solver(p,l,vp,vl,true,true),...
        @(p,l,vp,vl)slv.sego_solver(p,l,vp,vl,false,false),...       
        @(l,p)cvpr10.quat_assf(l,p),...
        @(p,vp)cvpr10.approx_pose_min(p,vp),...
        @(p,l,vp,vl,R3,t3)model.ba_min(p,l,vp,vl,R3,t3)
        };
    is_min = {
        true,...
        true,...        
        false,...
        true,...        
        true
        };
    
    is_pt_only = {
        false,...
        false,...        
        false,...
        true,...
        false
        };
    
    ids = {
        'EpiSEgo',...
        'PPSEgo',...        
        'AssF',...
        'Approx',...
        'BA'
        };
    
    methods = struct('run', fs, 'is_min', is_min, 'id', ids, 'is_pt_only', is_pt_only);
        
end