function methods = setup_methods

    addpath('/home/alexander/materials/pnpl/pnpl/opnp');
    
    fs = {        
        @(p,l,vp,vl)slv.sego_solver(p,l,vp,vl,true,true),...
        @(p,l,vp,vl)slv.sego_solver(p,l,vp,vl,false,false),...
        @(p,l,vp,vl)solve_stereo_minimal_full(p,l,vp,vl),...
        @(l,p)cvpr10.quat_assf(l,p),...
        @(p,vp)cvpr10.approx_pose_min(p,vp),...
        @(l,p)cvpr10.bruteforce(l,p),...
        };
    is_min = {
        true,...
        true,...
        true,...
        false,...
        true,...
        false
        };
    
    is_pt_only = {
        false,...
        false,...
        false,...
        false,...
        true,...
        false
        };
    
    ids = {
        'EpiSEgo',...
        'PPSEgo',...
        'GSEgo',...
        'AssF',...
        'Approx',...
        'OPnPL'
        };
    
    methods = struct('run', fs, 'is_min', is_min, 'id', ids, 'is_pt_only', is_pt_only);
        
end