function methods = setup_methods_ransac

    addpath('/home/alexander/materials/pnpl/pnpl/opnp');
    
    fs = {        
        @(p,l,vp,vl)slv.sego_solver(p,l,vp,vl,true,true),...                
        @(l,p)cvpr10.quat_assf(l,p),...
        @(p,vp)cvpr10.approx_pose_min(p,vp),...
        @(p)cvpr10.p3p_based(p),...
        };
    is_min = {        
        true,...        
        false,...
        true,...
        false
        };
    
    is_pt_only = {        
        false,...        
        false,...
        true,...
        true
        };
    
    ids = {
        'EpiSEgo',...                
        'AssF',...
        'Approx',...
        'P3P'
        };
    
    methods = struct('run', fs, 'is_min', is_min, 'id', ids, 'is_pt_only', is_pt_only);
        
end